server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /voicevox/ {
        resolver 127.0.0.11 valid=30s ipv6=off;
        rewrite ^/voicevox/(.*) /$1 break;
        set $voicevox_upstream http://voicevox:50021;
        proxy_set_header Host $host;
        proxy_pass $voicevox_upstream;
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
}
